# Generated by Django 6.0.6 on 2026-07-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Joint Secretary', 'Joint Secretary'), ('Sports Secretary', 'Sports Secretary'), ('Cultural Secretary', 'Cultural Secretary'), ('Treasurer', 'Treasurer'), ('Placement Secretary', 'Placement Secretary')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vote',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='election',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='election',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='election',
            name='title',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='election',
        ),
    ]
