# Generated by Django 6.0.6 on 2026-07-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_candidate_position_alter_vote_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Joint Secretary', 'Joint Secretary'), ('Treasurer', 'Treasurer'), ('Cultural', 'Cultural'), ('Sports', 'Sports'), ('Placement', 'Placement'), ('Brand Ambassador', 'Brand Ambassador')], max_length=50),
        ),
    ]
