# Generated by Django 6.0.6 on 2026-07-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_candidate_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.CharField(max_length=200),
        ),
    ]
