# Generated by Django 6.0.6 on 2026-07-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_candidate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Joint Secretary', 'Joint Secretary'), ('Treasurer', 'Treasurer'), ('Cultural', 'Cultural'), ('Sports', 'Sports'), ('Placement', 'Placement'), ('Brand Ambassador', 'Brand Ambassador')], db_index=True, max_length=50),
        ),
    ]
