# Generated by Django 6.0.6 on 2026-07-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_alter_candidate_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='position',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
